version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: /home/bbdcmf/php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - /home/bbdcmf/php:/var/www/html/
        ports:
            - 6060:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: project
            MYSQL_USER: admin
            MYSQL_PASSWORD: toor
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '7070:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
